import { Button } from '@chakra-ui/button';
import { Input } from '@chakra-ui/input';
import { Box, Center, Container, Heading, Text, SimpleGrid, VStack, HStack, Divider } from '@chakra-ui/layout';
import { Textarea } from '@chakra-ui/textarea';
import { faInstagram } from '@fortawesome/free-brands-svg-icons';
import { faGift } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Head from 'next/head';
import Link from 'next/link';
import Countdown from 'react-countdown';

import ClientCard from '../components/ClientCard';
import EventCard from '../components/EventCard';
import GuestBookItem from '../components/GuestBookItem';

export default function Home() {
  const mockDate = new Date('1 Sep 2022');
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <Center as="section" h="100vh">
          <Container as={VStack} spacing="24" maxW="container.md" textAlign="center">
            <Heading fontSize="24" color="#B66965">
              Dear Firdaus Algim, you are invited to
            </Heading>
            <Box>
              <Heading fontSize={{ sm: '28', lg: '36' }} color="main" opacity="80%">
                The Wedding Of
              </Heading>
              <Heading as="h1" fontFamily="Sacramento" fontSize={{ sm: '32', lg: '64' }} color="main">
                Addin &amp; Anis
              </Heading>
              <Heading fontSize="28" color="main" opacity="80%">
                September 3rd, 2022
              </Heading>
            </Box>
          </Container>
        </Center>

        <Box as="section" bg="bg" py="24">
          <Container as={VStack} spacing="32" maxW="container.lg" textAlign="center">
            <Box p="4" rounded="lg" bg="cardBg" color="white">
              <Text fontSize="lg">
                “Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu
                sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih
                dan sayang”
                <br />
                (QS. Ar- Rum 21)
              </Text>
            </Box>

            <SimpleGrid templateColumns={{ md: '1fr', lg: '4fr 1fr 4fr' }} gap="8" alignItems="center" w="80%">
              <ClientCard
                name={
                  <>
                    Muhammad
                    <br />
                    Syafruddin, S.P.
                  </>
                }
                parents={
                  <>
                    Putra Bpk. Joko Purnomo <br />
                    &amp; Ibu Retno Dyah Sundari
                  </>
                }
                socials={[
                  { title: 'instagram', logo: <FontAwesomeIcon icon={faInstagram} />, url: 'https://instagram.com' },
                ]}
              />
              <Text fontFamily="Sacramento" fontSize="6xl" color="main">
                &amp;
              </Text>
              <ClientCard
                name={
                  <>
                    Anisa Trias
                    <br />
                    Viyana, S.P.
                  </>
                }
                parents={
                  <>
                    Putri Bpk. Firman (Alm)
                    <br />
                    &amp; Ibu Ela Susyani
                  </>
                }
                socials={[
                  { title: 'instagram', logo: <FontAwesomeIcon icon={faInstagram} />, url: 'https://instagram.com' },
                ]}
              />
            </SimpleGrid>
          </Container>
        </Box>

        <Box as="section" py="20">
          <Container as={VStack} spacing="32" maxW="container.lg" textAlign="center">
            <SimpleGrid templateColumns={{ md: '1fr', lg: '4fr 1fr 4fr' }} gap="8" alignItems="center" w="full">
              <EventCard
                title="Akad Nikah"
                date="3"
                subDate="September 2022"
                place="Hotel handayani. Jl. Kembar No. 205 Indramayu, Jawa Barat"
                mapUrl="https://goo.gl/maps/N3FkGFM82YEUSmyX8"
              />
              <Divider orientation="vertical" />
              <EventCard
                title="Ngunduh Mantu"
                date="10"
                subDate="September 2022"
                place="Keden RT 01/RW 04, Sidoharjo, Wonogiri, Jawa Tengah"
                mapUrl="https://goo.gl/maps/2L2T9nf43w6ksgLC9"
              />
            </SimpleGrid>

            <VStack spacing="8">
              <Heading fontSize="3xl" color="main">
                Counting Down To The Big Day
              </Heading>
              <Countdown
                date={mockDate}
                renderer={(props) => (
                  <HStack spacing="3">
                    <VStack>
                      <Center boxSize="16" bg="#C88358" rounded="xl">
                        <Text fontFamily="Satisfy" fontSize="3xl" color="white" pt="2">
                          {props.days}
                        </Text>
                      </Center>
                      <Text color="main">Hari</Text>
                    </VStack>

                    <Text fontSize="2xl" color="main" pb="8">
                      :
                    </Text>

                    <VStack>
                      <Center boxSize="16" bg="#C88358" rounded="xl">
                        <Text fontFamily="Satisfy" fontSize="3xl" color="white" pt="2">
                          {props.hours}
                        </Text>
                      </Center>
                      <Text color="main">Jam</Text>
                    </VStack>

                    <Text fontSize="2xl" color="main" pb="8">
                      :
                    </Text>

                    <VStack>
                      <Center boxSize="16" bg="#C88358" rounded="xl">
                        <Text fontFamily="Satisfy" fontSize="3xl" color="white" pt="2">
                          {props.minutes}
                        </Text>
                      </Center>
                      <Text color="main">Menit</Text>
                    </VStack>

                    <Text fontSize="2xl" color="main" pb="8">
                      :
                    </Text>

                    <VStack>
                      <Center boxSize="16" bg="#C88358" rounded="xl">
                        <Text fontFamily="Satisfy" fontSize="3xl" color="white" pt="2">
                          {props.seconds}
                        </Text>
                      </Center>
                      <Text color="main">Detik</Text>
                    </VStack>
                  </HStack>
                )}
              />
            </VStack>

            <VStack spacing="6" color="main">
              <VStack>
                <Heading fontSize="3xl" color="main">
                  Wedding Gift
                </Heading>
                <Text w="60%" fontSize="lg">
                  Bagi keluarga dan sahabat yang ingin mengirimkan hadiah, silakan mengirimkannya melalui tautan
                  berikut:
                </Text>
              </VStack>

              <Button colorScheme="blue" leftIcon={<FontAwesomeIcon icon={faGift} />}>
                Kirim Hadiah
              </Button>
            </VStack>
          </Container>
        </Box>

        <Box as="section" bg="bg" py="24">
          <Container as={VStack} spacing="32" maxW="container.lg" textAlign="center">
            <SimpleGrid templateColumns={{ md: '1fr', lg: '2fr 1px 3fr' }} gap="8" alignItems="flex-start" w="full">
              <VStack spacing="4" alignItems="start">
                <Heading fontSize="2xl" color="main">
                  Guest Book
                </Heading>
                <VStack spacing="1" w="full" alignItems="start">
                  <Text color="main" opacity="95%">
                    Nama Pengirim
                  </Text>
                  <Input bg="white" w="full" />
                </VStack>

                <VStack spacing="1" w="full" alignItems="start">
                  <Text color="main" opacity="95%">
                    Pesan
                  </Text>
                  <Textarea bg="white" />
                </VStack>

                <Button colorScheme="green">Kirim Pesan</Button>
              </VStack>

              <Divider orientation="vertical" borderColor="main" borderStyle="dashed" />

              <VStack spacing="6" alignItems="start">
                <Heading fontSize="2xl" color="main">
                  Ucapan Tamu
                </Heading>

                <VStack spacing="4" w="full">
                  <GuestBookItem name="Cello Ananda" message="Congrats ya bro... semoga gue cepet nyusul haha.." />
                  <GuestBookItem
                    name="Mayada Nur"
                    message="Ga kerasa temen main udah nikah aja nih.. huhu selamat ya nis, semoga menjadi keluarga sakinah mawadah warohmah. Doain gue juga nis bisa nyusul di pelaminan. xixixi anw Happy Wedding Anisa & Addin"
                  />
                  <GuestBookItem name="Bagus Abi Cahya" message="Selamat Menempuh hidup baru addin & anisa" />

                  <Link href="#" passHref>
                    <Text as="a" color="main">
                      Lihat Semua...
                    </Text>
                  </Link>
                </VStack>
              </VStack>
            </SimpleGrid>
          </Container>
        </Box>
      </Box>
    </div>
  );
}
